services:

  wordpress:
    image: wordpress
    container_name: wordpress
    hostname: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  database:
    image: mysql:8.0
    container_name: database
    hostname: database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: examplerootpass 
    volumes:
      - database:/var/lib/mysql

volumes:
  wordpress:
    driver: local
  database:
    driver: local