name: deploy to lambda

on:
  push

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: npm install
        run: | 
          npm i -g bestzip
          npm i
      - name: deploy
        run: | 
          bestzip bundle.zip *
          aws lambda update-function-code --function-name=my-lambda-function --zip-file=fileb://bundle.zip
